version: '3'
services:
  redis-1:
    image: redis:latest
    container_name: redis-1
    restart: always
    entrypoint: redis-server /etc/redis/redis.conf
    network_mode: host
    volumes:
    - ./redis/data/data1:/data
    - ./redis/conf/redis-1.conf:/etc/redis/redis.conf

  redis-2:
    image: redis:latest
    container_name: redis-2
    restart: always
    entrypoint: redis-server /etc/redis/redis.conf
    network_mode: host
    volumes:
      - ./redis/data/data2:/data
      - ./redis/conf/redis-2.conf:/etc/redis/redis.conf

  redis-3:
    image: redis:latest
    container_name: redis-3
    restart: always
    entrypoint: redis-server /etc/redis/redis.conf
    network_mode: host
    volumes:
      - ./redis/data/data3:/data
      - ./redis/conf/redis-3.conf:/etc/redis/redis.conf

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    restart: always
    entrypoint: redis-sentinel /etc/redis/sentinel.conf
    network_mode: host
    volumes:
      - ./redis/conf/sentinel-1.conf:/etc/redis/sentinel.conf

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    restart: always
    entrypoint: redis-sentinel /etc/redis/sentinel.conf
    network_mode: host
    volumes:
      - ./redis/conf/sentinel-2.conf:/etc/redis/sentinel.conf

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    restart: always
    entrypoint: redis-sentinel /etc/redis/sentinel.conf
    network_mode: host
    volumes:
      - ./redis/conf/sentinel-3.conf:/etc/redis/sentinel.conf