version: "3"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64"
    container_name: es
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.9.2"
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
    - 5601:5601