version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    entrypoint: redis-server /etc/redis/redis.conf
    network_mode: host
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf